---
title: "Efficient data access for data reporting"
subtitle: "GBIF GB32 Global Nodes Training, Bogota, Colombia"
author: "Dag Endresen, https://orcid.org/0000-0002-2352-5497"
date:   "October 16-17, 2025"
output:
  html_document:
    keep_md: false
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction to using SQL with rgbif

## RGBIF SQL

```{r rgbif_sql eval=FALSE}
library(rgbif)
occ_download_sql("SELECT datasetKey, countryCode, COUNT(*) FROM occurrence WHERE continent = 'EUROPE' GROUP BY datasetKey, countryCode")
# https://docs.ropensci.org/rgbif/articles/gbif_sql_downloads.html
```

```{r rgbif_sql eval=FALSE}
# test if your download is set up correctly 
# occ_download_sql_prep("SELECT datasetKey, countryCode, COUNT(*) FROM occurrence WHERE continent = 'EUROPE' GROUP BY datasetKey, countryCode")
occ_download_sql("SELECT datasetKey, countryCode, COUNT(*) FROM occurrence WHERE continent = 'EUROPE' GROUP BY datasetKey, countryCode")
```

```{r rgbif_sql eval=FALSE}
# fetch the download and load the data
occ_download_get("0000967-240425142415019") %>%
  occ_download_import()
```

## Multi-dimension Counts

```{r rgbif_sql eval=FALSE}
sql <-
"
SELECT publishingcountry, specieskey, COUNT(*) as occurrence_count
FROM occurrence
WHERE publishingcountry IS NOT NULL AND specieskey IS NOT NULL
GROUP BY publishingcountry, specieskey
ORDER BY occurrence_count DESC;
"
occ_download_sql(sql)
```
